name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci --no-audit
      - run: npm run build
      # - run: npm run test
      #   env:
      #     CI: true
      # - run: npm run e2e
      #   env:
      #     CI: true
      - run: npm run lint
        env:
          CI: true
